/**
 * ==============================================================================
 * INDOPHARM — NORMALIZED PAYMENT EVENTS
 * ==============================================================================
 * Provider-agnostic event types emitted after webhook normalization.
 *
 * Adapters receive raw provider webhook payloads and MUST translate them
 * into one of these normalized events before the PaymentService processes them.
 *
 * The rest of IndoPharma must NEVER reference provider-specific event strings.
 * ==============================================================================
 */

/** Union of all normalized payment event types. */
export type NormalizedPaymentEventType =
  | 'PAYMENT_AUTHORIZED'
  | 'PAYMENT_CAPTURED'
  | 'PAYMENT_SUCCEEDED'
  | 'PAYMENT_FAILED'
  | 'PAYMENT_CANCELLED'
  | 'PAYMENT_REFUNDED'
  | 'PAYMENT_PARTIALLY_REFUNDED'
  | 'PAYMENT_DISPUTED'
  | 'PAYMENT_CHARGEBACK'
  | 'PAYMENT_REQUIRES_ACTION'
  | 'PAYMENT_STATUS_UNKNOWN';

/** Base structure shared by all normalized events. */
export interface NormalizedPaymentEventBase {
  /** IndoPharm normalized event type — never provider-specific */
  type: NormalizedPaymentEventType;
  /** Provider code (e.g. "mock", "checkout-com") */
  provider: string;
  /** Provider's unique event identifier (for idempotency checks) */
  providerEventId: string;
  /** Provider's payment/intent identifier */
  providerPaymentId: string;
  /** ISO timestamp the event was generated by the provider */
  providerTimestamp: Date;
  /** Safe metadata — NEVER include credentials */
  metadata?: Record<string, unknown>;
}

export interface PaymentAuthorizedEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_AUTHORIZED';
  amountMinorUnits: number;
  currency: string;
}

export interface PaymentCapturedEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_CAPTURED';
  capturedAmountMinorUnits: number;
  currency: string;
}

export interface PaymentSucceededEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_SUCCEEDED';
  amountMinorUnits: number;
  currency: string;
}

export interface PaymentFailedEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_FAILED';
  failureCode?: string;
  failureMessage?: string; // Safe, non-sensitive description
}

export interface PaymentCancelledEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_CANCELLED';
  reason?: string;
}

export interface PaymentRefundedEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_REFUNDED';
  refundAmountMinorUnits: number;
  currency: string;
  providerRefundId?: string;
}

export interface PaymentPartiallyRefundedEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_PARTIALLY_REFUNDED';
  refundAmountMinorUnits: number;
  currency: string;
  providerRefundId?: string;
}

export interface PaymentDisputedEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_DISPUTED';
  disputeAmountMinorUnits?: number;
  currency?: string;
  disputeReason?: string;
  providerDisputeId?: string;
}

export interface PaymentChargebackEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_CHARGEBACK';
  chargebackAmountMinorUnits?: number;
  currency?: string;
  providerDisputeId?: string;
}

export interface PaymentRequiresActionEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_REQUIRES_ACTION';
  actionUrl?: string;
}

export interface PaymentStatusUnknownEvent extends NormalizedPaymentEventBase {
  type: 'PAYMENT_STATUS_UNKNOWN';
  rawProviderStatus?: string;
}

/** Discriminated union of all possible normalized payment events. */
export type NormalizedPaymentEvent =
  | PaymentAuthorizedEvent
  | PaymentCapturedEvent
  | PaymentSucceededEvent
  | PaymentFailedEvent
  | PaymentCancelledEvent
  | PaymentRefundedEvent
  | PaymentPartiallyRefundedEvent
  | PaymentDisputedEvent
  | PaymentChargebackEvent
  | PaymentRequiresActionEvent
  | PaymentStatusUnknownEvent;

/**
 * Maps a normalized event type to the corresponding InternalPaymentStatus.
 * Used by the PaymentService when processing webhook events.
 */
import type { InternalPaymentStatus } from './payment-status';

export function eventTypeToStatus(
  eventType: NormalizedPaymentEventType
): InternalPaymentStatus | null {
  const map: Record<NormalizedPaymentEventType, InternalPaymentStatus | null> = {
    PAYMENT_AUTHORIZED: 'AUTHORIZED',
    PAYMENT_CAPTURED: 'CAPTURED',
    PAYMENT_SUCCEEDED: 'SUCCEEDED',
    PAYMENT_FAILED: 'FAILED',
    PAYMENT_CANCELLED: 'CANCELLED',
    PAYMENT_REFUNDED: 'REFUNDED',
    PAYMENT_PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
    PAYMENT_DISPUTED: 'DISPUTED',
    PAYMENT_CHARGEBACK: 'CHARGEBACK',
    PAYMENT_REQUIRES_ACTION: 'REQUIRES_ACTION',
    PAYMENT_STATUS_UNKNOWN: 'UNKNOWN',
  };
  return map[eventType] ?? null;
}
